import { query } from "./_generated/server";

export const getAllAppTables = query({
  args: {},
  handler: async (ctx) => {
    const [
      users,
      contactInfo,
      userPhotos,
      colleges,
      studentProfiles,
      providerProfiles,
      roommateProfiles,
      roommateMatches,
      apartmentListings,
      listingImages,
      savedListings,
      roommateGroups,
      groupMembers,
      groupMessages,
      groupSharedListings,
      groupListingVotes,
      reports,
      userSettings,
    ] = await Promise.all([
      ctx.db.query("users").collect(),
      ctx.db.query("contactInfo").collect(),
      ctx.db.query("userPhotos").collect(),
      ctx.db.query("colleges").collect(),
      ctx.db.query("studentProfiles").collect(),
      ctx.db.query("providerProfiles").collect(),
      ctx.db.query("roommateProfiles").collect(),
      ctx.db.query("roommateMatches").collect(),
      ctx.db.query("apartmentListings").collect(),
      ctx.db.query("listingImages").collect(),
      ctx.db.query("savedListings").collect(),
      ctx.db.query("roommateGroups").collect(),
      ctx.db.query("groupMembers").collect(),
      ctx.db.query("groupMessages").collect(),
      ctx.db.query("groupSharedListings").collect(),
      ctx.db.query("groupListingVotes").collect(),
      ctx.db.query("reports").collect(),
      ctx.db.query("userSettings").collect(),
    ]);

    return {
      generatedAt: new Date().toISOString(),
      tables: {
        users,
        contactInfo,
        userPhotos,
        colleges,
        studentProfiles,
        providerProfiles,
        roommateProfiles,
        roommateMatches,
        apartmentListings,
        listingImages,
        savedListings,
        roommateGroups,
        groupMembers,
        groupMessages,
        groupSharedListings,
        groupListingVotes,
        reports,
        userSettings,
      },
    };
  },
});
